//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking_Table
    {
        public string Ticket_ID { get; set; }
        public int Customer_ID { get; set; }
        public string SID { get; set; }
        public int NoOfTickets { get; set; }
    
        public virtual Customer_Table Customer_Table { get; set; }
        public virtual Schedule_Table Schedule_Table { get; set; }
    }
}
