//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Schedule_Table()
        {
            this.Booking_Table = new HashSet<Booking_Table>();
        }
    
        public string SID { get; set; }
        public string Route_ID { get; set; }
        public string Bus_ID { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.DateTime DateOfJourney { get; set; }
        public int AvailableSeats { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking_Table> Booking_Table { get; set; }
        public virtual BusDetails_Table BusDetails_Table { get; set; }
        public virtual Route_Table Route_Table { get; set; }
    }
}
